### ISSUE TITLE
Regarding Show the page on View Controller

### ISSUE THREAD

**Issue by IshuPhogat** [mysterioustrousers/MTPDF#16]
hi @atomkirk 
First thanks for this good pdf reader library.

I have a question not an issue. the question is:
could we show page directly on a view controller without convert it into the image?

is it possible or not?
If yes than would you like to elaborate it.
thanks in advance.

**Comment by atomkirk** [comment]
You can draw it directly into a `CGPDFContext` in a UIView. See "Draw a page to a CGPDFContext:" in the README
